### ISSUE TITLE
No such thing as a win32 folder in the source code folder

### ISSUE THREAD

**Issue by spaceyspacestar** [SSNTails/SRB2Proto#2]
I'm trying to compile the build via Visual Studio 2022 as there's a Visual Studio project in the source code, but as the engine version was 1.28 and it's lost to time, I can't seem to compile for win32 platforms. Assuming you were able to compile for release, did you forget to add the win32 folder or was it just not there when you compiled it?
Edit: In the solution itself, it does show, but upon opening it, it gives an error saying the file is not found
Image for reference:
![image](https://github.com/SSNTails/SRB2Proto/assets/41171313/d1df104b-c136-4b41-af79-bc511c792f8f)

**Comment by SSNTails** [comment]
Weird! My local git client absolutely refuses to add the win32 folder for some reason and it was excluded. Thankfully, GitHub has a web upload feature.
