### ISSUE TITLE
Crash on startup when trying to build from source

### ISSUE THREAD

**Issue by TheAwesomeZave** [SSNTails/SRB2Proto#6]
The game boots up, loads everything, plays the music, does the screen wipe and immediately after, crashes.

![image](https://github.com/user-attachments/assets/68677fb2-4c05-4b93-9fc7-b5b7584494cf)

I am running it with "Debug x86" because Win32 wasn't showing up for some reason (and they're appearently synonyms? I'm relatively new to Visual Studio) and obviously the working directory is set up correctly

**Comment by SSNTails** [comment]
If you run it in the debugger with Visual Studio, then click 'Retry', where in the code does it drop you?

**Comment by TheAwesomeZave** [comment]
![image](https://github.com/user-attachments/assets/ab01ecae-c269-44a2-859b-065cc9852524)
It takes me to stricmp.cpp at line 99. I think I might have set up Visual Studio wrong unfortunately :(

**Comment by SSNTails** [comment]
You need to follow it up the stack to when it hits srb2 code, not the C library stricmp.

**Comment by TheAwesomeZave** [comment]
My bad, not sure what I was thinking :/
It takes me to R_things.c at line 1260.
![image](https://github.com/user-attachments/assets/3fd1e0fe-941f-4cf8-8e8d-380a61302690)
The debugger shows that skins[i] is "sonic" and skinname is NULL.
![image](https://github.com/user-attachments/assets/273f17e1-1be2-43d7-aa14-8f06da9d9b82)

**Comment by SSNTails** [comment]
My first guess is that it’s not finding some of the files/WADs you need. Make sure you have the working directory set properly in visual studio (project properties).

**Comment by TheAwesomeZave** [comment]
It's set up to load srb2.wad, test2.wad, srb2z1m1_restored.wad (probably not important), and tails.wad after your suggestion. tails.wad might have given the debugger more data now though.
![image](https://github.com/user-attachments/assets/5370c90a-a880-43de-a9a8-d883b9f623b3)

![image](https://github.com/user-attachments/assets/7b6a9b85-d3ae-4ee3-882d-86d4d995ff70)

**Comment by SSNTails** [comment]
You’re adding the WADs in the wrong order. These old versions can be very picky about that. Take another look at the readme.

**Comment by TheAwesomeZave** [comment]
I changed it to be the same order as the readme, but it's still giving the exact same error.
![image](https://github.com/user-attachments/assets/960ce7c4-015e-4355-956d-7513a3bf8bf0)
![image](https://github.com/user-attachments/assets/42526cd0-9cf8-4672-a78c-cbfe9bd97ffc)

**Comment by SSNTails** [comment]
Try deleting your autoexec.cfg and config.cfg, maybe?

Otherwise, we could do a screen share on discord. I’m positive that this should work and something is just missing.

**Comment by TheAwesomeZave** [comment]
That didn't fix it. Also, I'm really sorry to say that I don't have a Discord. :(
I did record myself getting the error, though.
https://drive.google.com/file/d/1hfpQKMTz8-M3-MOhPSubPB5AdgKD9fMf/view?usp=sharing

**Comment by SSNTails** [comment]
Ok, here’s another idea… could you zip up your /Binaries folder (where you put the wads and stuff) and stick it on Google Drive? I’ll then do a fresh clone and try running it with the exact same folder contents as you.

**Comment by TheAwesomeZave** [comment]
Uploaded it!
https://drive.google.com/file/d/1j0z_Xz8OyIHacOxkd_ClhIWOExOO-4Mi/view?usp=sharing

**Comment by SSNTails** [comment]
Very strange, it's happening to me now, too. I wonder if the pull requests to get it working on Linux actually broke it on Windows!

Try rolling back to this commit:
https://github.com/SSNTails/SRB2Proto/commit/9aebd129817b1fc72d00838f0b07eaa0743b67c1

You can do so with the command:
git reset 8d319c5

and then 'undo' all of the ''changes' in the git window

**Comment by TheAwesomeZave** [comment]
Thank you!

**Comment by bitten2up** [comment]
looking into it and posting this for my personal reference...

all the changes that could affect windows `r_data.c` had an `alloca` changed into an `malloc` (and a `free`), a lot of increment changes, `m_fixed.c` and `m_fixed.h` had tiny changes for `NOASM`, splitscreen was disabled in `doomdef.h`, a random return was added in `command.c:132` which isn't required to run on linux (not sure why), `byteptr.h` was pretty much replaced with a newer version, `r_draw8.c` had two `NOASM` functions added, `d_netcmd.c` had two `memcpy` functions removed accidentally

I'll make a draft pr with the changes I'm making.

**Comment by bitten2up** [comment]
I'm not sure if this is my falt...

in `Got_NameAndcolor` the `cp` pointer becomes `NULL` for some reason
![image](https://github.com/user-attachments/assets/5876d5e7-3594-4f2b-b578-afbf669f2e4c)

**Comment by bitten2up** [comment]
![image](https://github.com/user-attachments/assets/d7b220d5-7670-414e-a8b5-18908266c4c5)
well thats better than nothing ig...

**Comment by bitten2up** [comment]
i think i found it... linux was having issues in the exact same spot, so i replaced bytepointer.h
